backend:
  name: github
  repo: Ndidi/LightbulbCMS

media_folder: static/assets

publish_mode: editorial_workflow

collections:
  - name: pages
    label: Pages
    files:
      - file: "src/pages/index/index.md"
        label: "Index"
        name: "index"
        delete: false
        fields:
          - {label: "Template Key", name: "templateKey", default: "index-page"}
          - {label: "Path", name: "path", default: "/indexed"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}      
          - {label: "Cat", name: "cat", widget: "categories"}      
            
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }