backend:
  name: github
  repo: Ndidi/LightbulbCMS

media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: Pages
    files:
      - file: "src/pages/index/index.md"
        label: "Index"
        name: "index"
        delete: false
        fields:
          - {label: "Template Key", name: "templateKey", default: "index-page", widget: hidden}
          - {label: "Path", name: "path", default: "/"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - label: "Video"
            name: "video"
            widget: "object"
            fields:
              - {label: "Source", name: "source", widget: "string"}
              - {label: "Poster", name: "poster", widget: "string"}
          - label: "Client Logos"
            name: "clientLogos"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
          - label: "Stories"
            name: "stories"
            widget: "list"
            fields: [{label: "Story Heading", name: "storyHeading", widget: string}, {label: "Story Body", name: "storyBody", widget: string}]
          - {label: "Centered Text", name: "centeredText", widget: "object", fields: [{label: "Heading", name: "heading", widget: "string"}, {label: "Body", name: "body", widget: "string"}, {label: "Link", name: "link", widget: "object", fields: [{label: "Link Name", name: "linkName", widget: "string"}, {label: "Link", name: "link", widget: "string"}]}]}
          - {label: "Features", name: "features", widget: "list", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Text", name: "text", widget: "string"}, {label: "Description", name: "description", widget: "string"}]}
          - label: "Tabbed Top Features"
            name: "tabbedTopFeatures"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "SubTitle", name: "subtitle", widget: "string"}
              - {label: "Tab 1", name: "tab1", widget: "string"}
              - {label: "Image 1", name: "image1", widget: "image"}
              - {label: "Tab 2", name: "tab2", widget: "string"}
              - {label: "Image 2", name: "image2", widget: "image"}
              - {label: "Tab 3", name: "tab3", widget: "string"}
              - {label: "Image 3", name: "image3", widget: "image"}              
          - label: "Testimonial"
            name: "testimonial"
            widget: "object"
            fields:
              - {label: "Quote", name: "quote", widget: "string"}
              - {label: "Author", name: "author", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
          - {label: "Full Page Message", name: "fullPageMessage", widget: "string"}
      - file: "src/pages/data-storytelling/data-storytelling.md"
        label: "Data Storytelling"
        name: "dataStorytelling"
        delete: false
        create: true
        fields:
          - {label: "Template Key", name: "templateKey", default: "data-storytelling-page", widget: hidden}
          - {label: "Path", name: "path", default: "/what-is-data-storytelling"}
          - {label: "Title", name: "title", widget: "string"}
      - file: "src/pages/request-demo/request-demo.md"
        label: "Request Demo"
        name: "requestDemo"
        delete: false
        fields:
          - {label: "Template Key", name: "templateKey", default: "request-demo-page", widget: hidden}
          - {label: "Path", name: "path", default: "/request-demo"}
          - {label: "Blurb", name: "blurb", widget: "string"}
          - {label: "Detail1", name: "detail1", widget: "string"}
          - {label: "Detail2", name: "detail2", widget: "string"}
          - {label: "Detail3", name: "detail3", widget: "string"}
      - file: "src/pages/thank-you/thank-you.md"
        label: "Thank You"
        name: "thankYou"
        delete: false
        fields:
          - {label: "Template Key", name: "templateKey", default: "thank-you-page", widget: hidden}
          - {label: "Path", name: "path", default: "/thank-you", widget: hidden}
          - {label: "Title", name: "title", default: "Thanks for reaching out to us!"}
          - {label: "Subtitle", name: "subtitle", default: "One of our friendly Account Executives will be in touch with you shortly."}
      - file: "src/pages/product/product.md"
        label: "Product"
        name: "product"
        delete: false
        fields:
          - {label: "Template Key", name: "templateKey", default: "product-page", widget: hidden}
          - {label: "Path", name: "path", default: "/product", widget: hidden}
          - {label: "Title", name: "title"}
          - {label: "Subtitle", name: "subtitle"}
          - label: "Image and Text"
            name: "imageText"
            widget: "object"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Text", name: "text", widget: "string"}
          - label: "Text and Image"
            name: "textImage"
            widget: "object"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
          - label: "Centered Content"
            name: "centeredContent"
            widget: "object"
            fields:
              - {label: "Title", name: "title"}
              - {label: "Subtitle", name: "subtitle"}
              - {label: "Image", name: "image", widget: "image"}
  - name: sections
    label: Sections
    files:
      - file: "src/layouts/standard-layout/standard-layout.md"
        label: "Standard Layout"
        name: "standard-Layout"
        fields:
          - {label: "Template Key", name: "templateKey", default: "standard-layout", widget: hidden}
          - label: "Navbar Items"
            name: "navBarItems"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "href", name: "href", widget: "string"}
              - label: "SubItems"
                name: "navItem"
                widget: "list"
                fields:
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "href", name: "href", widget: "string"}